Hw11 telnet client
soypita/otus_golang_homework pull request #13
Opened 2020-05-28 17:04 UTC by soypita

## Домашнее задание №11 «Клиент TELNET»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-05-30 07:18 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/63139/6035/

Здравствуйте!
Давайте вместе подумаем, как это можно сделать чуть проще.
\+ не вижу обработки SIGINT

6 / 10

2020-05-30 07:18 UTC, Antonboom commented on hw11_telnet_client/test.sh
> +echo "PASS"
newline

2020-05-30 07:18 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	timeoutVar := flag.String("timeout", "10s", "connection timeout for client in seconds")
https://golang.org/pkg/flag/#Duration

2020-05-30 07:18 UTC, Antonboom commented on hw11_telnet_client/main.go
> +func runProcess(timeoutVar *string, args []string) error {
не вижу кода, обрабатывающего сигнал от OS

2020-05-30 07:18 UTC, Antonboom commented on hw11_telnet_client/telnet.go
> +	<-t.sendCh
можно ли объединить sendCh + doneCh + errorCh + логику получения сигнала от ОС во что-то одно?

2020-05-31 13:30 UTC, soypita commented on hw11_telnet_client/test.sh
> +echo "PASS"
Исправлено

2020-05-31 13:30 UTC, soypita commented on hw11_telnet_client/main.go
> +	timeoutVar := flag.String("timeout", "10s", "connection timeout for client in seconds")
Исправлено

2020-05-31 13:31 UTC, soypita commented on hw11_telnet_client/main.go
> +func runProcess(timeoutVar *string, args []string) error {
Добавил

2020-05-31 13:31 UTC, soypita commented on hw11_telnet_client/telnet.go
> +	<-t.sendCh
Исправлено, вынес в одну общую рабочую горутину, которая следит за всем.

2020-05-31 13:31 UTC, soypita commented
@Antonboom Добрый день, исправил замечания, подправил основные методы

2020-06-03 06:26 UTC, Antonboom approved these changes
Добрый день!

Спасибо за работу, стало гораздо приятнее.
Местами овер-инжиниринг, конкретные вопросы-замечания привел.

Принято
8 / 10

2020-06-03 06:26 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	for {
нельзя ли цикл перенести внутрь Send/Receive?

по идее на этом уровне должна остаться только логика с конкуррентностью

2020-06-03 06:26 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	go func() {
зачем здесь горутина и цикл в ней?

2020-06-03 06:26 UTC, Antonboom commented on hw11_telnet_client/main.go
> +				if err != nil {
судя по коду ниже, сюда не может придти not nil ошибка

2020-06-03 06:26 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	wg := &sync.WaitGroup{}
зачем здесь указатель?
а не просто
```
var wg sync.WaitGroup
```
?

2020-06-03 06:26 UTC, Antonboom commented on hw11_telnet_client/main.go
> +				return
signal.Stop

2020-06-03 06:26 UTC, Antonboom commented on hw11_telnet_client/telnet.go
> +			err = fmt.Errorf(connectCloseMsg)
return errors.New()

2020-06-03 06:26 UTC, Antonboom commented on hw11_telnet_client/telnet.go
> +	err := t.conn.Close()
return t.conn.Close()

2020-06-11 16:50 UTC, merged