Hw12 13 14 15 calendar
soypita/otus_golang_homework pull request #15
Opened 2020-06-07 13:37 UTC by soypita

## Домашнее задание №12 «Заготовка сервиса Календарь»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Понятность и чистота кода (включая факт, что проект разбит
на пакеты по определенной логике) - до 2 баллов
- [ ] Реализовано конфигурирование сервиса - 1 балл
- [ ] Используется логгер и он настраивается из конфига - 1 балл
- [ ] Запускается простой HTTP-сервер - 1 балл
- [ ] Присутствуют юнит-тесты - 1 балл

Реализовано хранилище:
- [ ] in-memory - 1 балл
- [ ] sql + миграции - 2 балла

#### Зачёт от 7 баллов

2020-06-19 14:53 UTC, farir1408 requested changes

2020-06-19 14:53 UTC, farir1408 commented on hw12_13_14_15_calendar/cmd/calendar/calendar.go
> +package main
Лучше данный файл назвать main.go.

2020-06-19 14:53 UTC, farir1408 commented on hw12_13_14_15_calendar/internal/repository/events_repository.go
> +type EventsRepository interface {
Интерфейс находится в пакете с реализацией, теряется его смысл. Не вижу структуры Calendar, в которой внутри есть зависимость от интерфейса стореджа. По сути Calendar - это бизнес-логика (БЛ). И вот внутри БЛ зависит от хранилища, но не от какого-то определённого, а от интерфейса. Инмемори и постгрес реализации этого интерфейса. CRUD ручки calendar внутри должны вызывать CRUD ручки стореджа.

2020-06-19 14:54 UTC, farir1408 commented
Здравствуйте!

Спасибо за выполнение домашнего задания.

Обратите сейчас больше внимание на внутреннюю логику, а не на интерфейс api - http.

2020-06-20 10:47 UTC, soypita commented on hw12_13_14_15_calendar/cmd/calendar/calendar.go
> +package main
Поправил

2020-06-20 10:48 UTC, soypita commented on hw12_13_14_15_calendar/internal/repository/events_repository.go
> +type EventsRepository interface {
Разнес интерфейс репозитория и конкретные реализации по разным пакетам.
Добавил круд обертку сервиса календаря над репозиторием

2020-06-20 10:48 UTC, soypita commented
> Здравствуйте!
> 
> Спасибо за выполнение домашнего задания.
> 
> Обратите сейчас больше внимание на внутреннюю логику, а не на интерфейс api - http.

@farir1408 Здравствуйте! Исправил основные замечания

2020-06-23 09:14 UTC, farir1408 submitted a review, later dismissed

2020-06-23 09:14 UTC, farir1408 commented on hw12_13_14_15_calendar/internal/services/calendar/calendar.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
Круто что используете контекст, но он должен проходить по всему запросу через все функции. Так что давайте его сделаем первым параметром в сигнатуре функции. `CreateEvent(ctx context.Context, ev *models.Event)`

2020-06-23 09:15 UTC, farir1408 commented
Здравствуйте!

Спасибо за выполнение домашнего задания.

Отличная работа, принято 10/10.

2020-06-23 10:05 UTC, merged